const W = 'write';

const MANIFEST = [
  { m: 'POST', p: '/sow/templates', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/templates/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/templates/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/standard/component/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/standard/operation', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/standard/operation/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/standard/operation/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/standard/operation/:id/attachments', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/standard/attachment/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/nnva/base', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/nnva/base/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/nnva/base/:id', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/nnva/standard/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/operationcard/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/documentnos', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/create', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/history-order/:id/info', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/history-order/:id', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/drafts/:context/:refKey', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/drafts/:context/:refKey', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/saved', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/saved/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/saved/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/progress-history', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/parts', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/parts/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/parts/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/operations', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/operations/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/operations/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/sow', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/sow/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/createex', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/upsert', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/updateex/:id', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/finish', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/:id', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/:id', f: 'sow_management', a: W },

  { m: 'POST', p: '/sow/operations/:id/subtasks', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/operations/:id/subtasks/batch', f: 'sow_management', a: W },
  { m: 'PUT', p: '/sow/subtasks/:id', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/subtasks/:id/progress', f: 'sow_management', a: W },

  { m: 'POST', p: '/sow/subtasks/import', f: 'sow_management', a: W },
  { m: 'POST', p: '/sow/subtask-standards/import', f: 'sow_management', a: W },
  { m: 'DELETE', p: '/sow/subtask-standards/:id', f: 'sow_management', a: W },

  { m: 'POST', p: '/sow/subcont-marks', f: 'sow_subcont', a: W },
  { m: 'DELETE', p: '/sow/subcont-marks/:id/:opno', f: 'sow_subcont', a: W },

  { m: 'POST', p: '/sow-schedule/shift-rules', f: 'shift_rules', a: W },
  { m: 'PUT', p: '/sow-schedule/shift-rules/:id', f: 'shift_rules', a: W },
  { m: 'DELETE', p: '/sow-schedule/shift-rules/:id', f: 'shift_rules', a: W },
  { m: 'POST', p: '/sow-schedule/batches', f: 'sow_scheduling', a: W },
  { m: 'DELETE', p: '/sow-schedule/batches/:id', f: 'sow_scheduling', a: W },
  { m: 'PUT', p: '/sow-schedule/capacity', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/capacity', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/overtime', f: 'sow_scheduling', a: W },
  { m: 'PUT', p: '/sow-schedule/overtime/:id', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/overtime/:id/approve', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/overtime/:id/reject', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/overtime/:id/assign', f: 'sow_scheduling', a: W },
  { m: 'DELETE', p: '/sow-schedule/overtime/:id', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/operation-status', f: 'sow_verification', a: W },
  { m: 'DELETE', p: '/sow-schedule/operation-status/:id', f: 'sow_verification', a: W },
  { m: 'POST', p: '/sow-schedule', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/:id/reschedule', f: 'sow_scheduling', a: W },
  { m: 'POST', p: '/sow-schedule/:id/reorder', f: 'sow_scheduling', a: W },
  { m: 'PUT', p: '/sow-schedule/:id', f: 'sow_scheduling', a: W },
  { m: 'DELETE', p: '/sow-schedule/:id', f: 'sow_scheduling', a: W },

  { m: 'POST', p: '/usernfc', f: 'nfc_users', a: W },
  { m: 'PUT', p: '/usernfc/update', f: 'nfc_users', a: W },
  { m: 'PUT', p: '/usernfc/mode/:id', f: 'nfc_users', a: W },
  { m: 'PUT', p: '/usernfc/nfcedit/:id', f: 'nfc_users', a: W },
  { m: 'PUT', p: '/usernfc/inactive/:snssb', f: 'nfc_users', a: W },
  { m: 'PUT', p: '/usernfc/:id', f: 'nfc_users', a: W },
  { m: 'DELETE', p: '/usernfc/:id', f: 'nfc_users', a: W },

  { m: 'PUT', p: '/timesheet/validation', f: 'timesheet_validation', a: W },
  { m: 'POST', p: '/timesheet/post-to-sap', f: 'timesheet_validation', a: W },
  { m: 'PUT', p: '/timesheet/updateadmin/:id', f: 'timesheet_validation', a: W },
  { m: 'PATCH', p: '/timesheet/:id', f: 'timesheet_validation', a: W },
  { m: 'DELETE', p: '/timesheet/:id', f: 'timesheet_validation', a: W },

  { m: 'POST', p: '/process-control/categories', f: 'machine_hours', a: W },
  { m: 'PUT', p: '/process-control/categories/:id', f: 'machine_hours', a: W },
  { m: 'DELETE', p: '/process-control/categories/:id', f: 'machine_hours', a: W },
  { m: 'POST', p: '/process-control/parameters', f: 'machine_hours', a: W },
  { m: 'PUT', p: '/process-control/parameters/:id', f: 'machine_hours', a: W },
  { m: 'DELETE', p: '/process-control/parameters/:id', f: 'machine_hours', a: W },
  { m: 'POST', p: '/process-control/choices', f: 'machine_hours', a: W },
  { m: 'PUT', p: '/process-control/choices/:id', f: 'machine_hours', a: W },
  { m: 'DELETE', p: '/process-control/choices/:id', f: 'machine_hours', a: W },
  { m: 'POST', p: '/process-control/items', f: 'machine_hours', a: W },
  { m: 'PUT', p: '/process-control/items/:id', f: 'machine_hours', a: W },
  { m: 'DELETE', p: '/process-control/items/:id', f: 'machine_hours', a: W },
  { m: 'PATCH', p: '/process-control/validate/:id', f: 'machine_hours', a: W },
  { m: 'POST', p: '/process-control', f: 'machine_hours', a: W },
  { m: 'PUT', p: '/process-control/:id', f: 'machine_hours', a: W },
  { m: 'DELETE', p: '/process-control/:id', f: 'machine_hours', a: W },

  { m: 'POST', p: '/receiving-shipment/customers', f: 'receiving_shipment', a: W },
  { m: 'POST', p: '/receiving-shipment/part-categories', f: 'receiving_shipment', a: W },
  { m: 'POST', p: '/receiving-shipment', f: 'receiving_shipment', a: W },
  { m: 'PUT', p: '/receiving-shipment/:id', f: 'receiving_shipment', a: W },
  { m: 'DELETE', p: '/receiving-shipment/:id', f: 'receiving_shipment', a: W },

  { m: 'POST', p: '/component-tracking/buffers', f: 'component_tracking', a: W },
  { m: 'PATCH', p: '/component-tracking/buffers/priorities', f: 'component_tracking', a: W },
  { m: 'PATCH', p: '/component-tracking/buffers/:id/note', f: 'component_tracking', a: W },

  { m: 'POST', p: '/kanban/refresh', f: 'kanban_board', a: W },

  { m: 'PATCH', p: '/consumable/control/:id/approve', f: 'consumable_control', a: W },
  { m: 'PATCH', p: '/consumable/control/:id/close', f: 'consumable_control', a: W },
  { m: 'PATCH', p: '/consumable/control/items/:id/quantity', f: 'consumable_control', a: W },
  { m: 'PATCH', p: '/consumable/control/items/:id/reject', f: 'consumable_control', a: W },
  { m: 'POST', p: '/consumable/request', f: 'consumable_control', a: W },
  { m: 'POST', p: '/consumable/stock/upload', f: 'consumable_control', a: W },

  { m: 'POST', p: '/tools/reservations', f: 'tools_management', a: W },
  { m: 'PATCH', p: '/tools/reservations/:id/:action', f: 'tools_management', a: W },
  { m: 'POST', p: '/tools/transactions/borrow', f: 'tools_management', a: W },
  { m: 'PATCH', p: '/tools/transactions/:id/return', f: 'tools_management', a: W },
  { m: 'POST', p: '/tools/handovers', f: 'tools_management', a: W },
  { m: 'PATCH', p: '/tools/handovers/:id/accept', f: 'tools_management', a: W },
  { m: 'PATCH', p: '/tools/handovers/:id/reject', f: 'tools_management', a: W },
  { m: 'PATCH', p: '/tools/:id', f: 'tools_management', a: W },

  { m: 'POST', p: '/ms-project/bay-schedules', f: 'bay_scheduling', a: W },
  { m: 'DELETE', p: '/ms-project/bay-schedules/:id', f: 'bay_scheduling', a: W },
  { m: 'PUT', p: '/ms-project/bay-schedules/group/:id', f: 'bay_scheduling', a: W },
  { m: 'DELETE', p: '/ms-project/bay-schedules/group/:id', f: 'bay_scheduling', a: W },

  { m: 'PATCH', p: '/ms-project/sow-orders/:id/operations/people', f: 'bay_scheduling', a: W },

  { m: 'PUT', p: '/ms-project/projects/:id/tasks/map-operation', f: 'msproject_mapping', a: W },

  { m: 'POST', p: '/ms-project/projects', f: 'msproject_collab', a: W },
  { m: 'POST', p: '/ms-project/projects/bulk-load', f: 'msproject_collab', a: W },
  { m: 'POST', p: '/ms-project/projects/:id/file', f: 'msproject_collab', a: W },
  { m: 'POST', p: '/ms-project/projects/:id/checkout', f: 'msproject_collab', a: W },
  { m: 'POST', p: '/ms-project/projects/:id/heartbeat', f: 'msproject_collab', a: W },
  { m: 'PUT', p: '/ms-project/projects/:id/sync', f: 'msproject_collab', a: W },
  { m: 'POST', p: '/ms-project/projects/:id/publish', f: 'msproject_collab', a: W },
  { m: 'POST', p: '/ms-project/projects/:id/checkin', f: 'msproject_collab', a: W },
  { m: 'PUT', p: '/ms-project/projects/:id/status', f: 'msproject_collab', a: W },
  { m: 'PUT', p: '/ms-project/projects/:id', f: 'msproject_collab', a: W },
  { m: 'PUT', p: '/ms-project/projects/:id/tasks/:task_id', f: 'msproject_collab', a: W },
  { m: 'DELETE', p: '/ms-project/projects/:id', f: 'ms_project_admin', a: W },

  { m: 'POST', p: '/ms-project/projects/:id/force-checkin', f: 'ms_project_admin', a: W },
  { m: 'POST', p: '/ms-project/calendars/refresh-from-shifts', f: 'ms_project_admin', a: W },
  { m: 'POST', p: '/ms-project/resources/refresh', f: 'ms_project_admin', a: W },
  { m: 'POST', p: '/ms-project/projects/:id/resources', f: 'ms_project_admin', a: W },
  { m: 'DELETE', p: '/ms-project/projects/:id/resources/:rid', f: 'ms_project_admin', a: W },

  { m: 'POST', p: '/dashboard/refresh-order-matviews', f: 'dashboard', a: W },

  { m: 'POST', p: '/dashboard/sap-ops/enqueue', f: 'sap_log', a: W },
  { m: 'POST', p: '/dashboard/sap-ops/post-corrections', f: 'sap_log', a: W },

  { m: 'POST', p: '/dashboard/machine-hours-override', f: 'machine_hours', a: W },

  { m: 'PUT', p: '/config/rules', f: 'config_rules', a: W },

  { m: 'PUT', p: '/ews/issue-log/:id/resolve', f: 'ews', a: W },
  { m: 'POST', p: '/ews/issue-log/generate', f: 'ews', a: W },
  { m: 'POST', p: '/ews/notifications/:id/played', f: 'ews', a: W },

  { m: 'PUT', p: '/ews/roster/status', f: 'roster_operator', a: W },
  { m: 'PUT', p: '/ews/roster/config/workday', f: 'roster_operator', a: W },
  { m: 'PUT', p: '/ews/roster/group', f: 'roster_operator', a: W },
  { m: 'POST', p: '/ews/roster/generate', f: 'roster_operator', a: W },

  { m: 'POST', p: '/ews/roster/lock', f: 'roster_operator', a: W },
  { m: 'POST', p: '/ews/roster/lock/:id/cancel', f: 'roster_operator', a: W },

  { m: 'POST', p: '/auth/users', f: 'manage_users', a: W },
  { m: 'PUT', p: '/auth/users/:id', f: 'manage_users', a: W },
  { m: 'DELETE', p: '/auth/users/:id', f: 'manage_users', a: W },
  { m: 'PUT', p: '/auth/users/:id/permissions', f: 'manage_users', a: W },
];

const ALLOWLIST = [
  { m: 'POST', p: '/auth/login' },
  { m: 'POST', p: '/auth/change-password' },

  { m: 'POST', p: '/timesheet' },
  { m: 'PUT', p: '/timesheet/checkout' },
  { m: 'PUT', p: '/timesheet/checkout-unprod' },
  { m: 'PUT', p: '/timesheet/checkoutid' },

  { m: 'POST', p: '/device-heartbeat' },

  { m: 'POST', p: '/sow/planhours/multi' },
];

module.exports = { MANIFEST, ALLOWLIST };
