FROM python:3.11-slim


WORKDIR /app

COPY requirements.heartbeat.txt ./
RUN pip install --no-cache-dir -r requirements.heartbeat.txt

COPY sync_machine_heartbeat.py ./

CMD ["python", "-u", "sync_machine_heartbeat.py"]
